[phases.setup]
nixPkgs = ["python311", "pip", "nodejs_18"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "npm ci"
]

[phases.build]
cmds = []

[start]
cmd = "gunicorn backend.wsgi --bind 0.0.0.0:$PORT"
