[phases.setup]
nixPkgs = ["python311", "nodejs_18"]

[phases.install]
cmds = ["pip install -r requirements.txt", "npm ci"]

[phases.build]
cmds = []

[phases.start]
cmd = "gunicorn backend.wsgi --log-file -"
