[phases.setup]
nixPkgs = ["python311", "postgresql", "nodejs_18", "pipenv"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn backend.wsgi --log-file -"
