[phases.setup]
nixPkgs = ["python311", "nodejs_18"]

[phases.install]
cmds = [ "pip install -r requirements.txt",
  "npm ci",
  "which python3",
  "which gunicorn"]

[phases.build]
cmds = []

[phases.start]
cmd = "gunicorn backend.wsgi --log-file -"
